name: Build Dumper Binaries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Build Binaries
      shell: cmd
      run: |
        set SRC=themida_dumper_universal.c
        set FLAGS=-O2 -s -static -lntdll
        
        :: Build x64
        x86_64-w64-mingw32-gcc %SRC% %FLAGS% -DDEFAULT_MODE=MODE_THEMIDA   -o themida_dumper_x64.exe
        x86_64-w64-mingw32-gcc %SRC% %FLAGS% -DDEFAULT_MODE=MODE_VMPROTECT -o vmprotect_dumper_x64.exe
        x86_64-w64-mingw32-gcc %SRC% %FLAGS% -DDEFAULT_MODE=MODE_RUNTIME   -o runtime_dumper_x64.exe
        
        :: Build x86
        i686-w64-mingw32-gcc %SRC% %FLAGS% -DDEFAULT_MODE=MODE_THEMIDA   -o themida_dumper_x86.exe
        i686-w64-mingw32-gcc %SRC% %FLAGS% -DDEFAULT_MODE=MODE_VMPROTECT -o vmprotect_dumper_x86.exe
        i686-w64-mingw32-gcc %SRC% %FLAGS% -DDEFAULT_MODE=MODE_RUNTIME   -o runtime_dumper_x86.exe

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dumper-binaries
        path: "*.exe"
